apps/noticias/urls.py
from django.urls import path
from . import views

app_name = 'noticias'

urlpatterns = [
	
	path('', views.Listar_Noticias, name = 'listar'),

	path('Detalle/<int:pk>', views.Detalle_Noticias, name = 'detalle'),
	
	path('Comentario/', views.Comentar_Noticia, name = 'comentar'),
	
]

apps/usuarios/urls.py
from django.urls import path

from . import views

app_name = 'usuarios'

urlpatterns = [
    
    path('registro/', views.Registro.as_view(), name = 'registro'),

   

]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
#URL LOGIN
from django.contrib.auth import views as auth

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls, name = 'admin'),
    # 1 PARAMETROS ES EL TEXTO DE LA URL
    # 2 LA VISTA QUE VA EJECUTAR
    # 3 ES EL NOMBRE LA URL (aun no lo usamos)
    path('', views.Home, name = 'home'),
    #No necesariamente estos 3 valores (parametors) se deben llamar igual
    path('Nosotros/', views.Nosotros, name = 'nosotros'),
   

    #LOGIN
    path('login/',auth.LoginView.as_view(template_name='usuarios/login.html'),name='login'),
    path('logout/',auth.LogoutView.as_view(),name="logout"),
    

    # URL DE APLICACION
    path('Noticias/', include('apps.noticias.urls')),
    path('Usuario/',include('apps.usuarios.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/noticias/models.py
from django.db import models
from apps.usuarios.models import Usuario

class Categoria(models.Model):
	nombre = models.CharField(max_length = 60)

	def __str__(self):
		return self.nombre

class Noticia(models.Model):

	titulo = models.CharField(max_length = 150)
	cuerpo = models.TextField()
	imagen = models.ImageField(upload_to = 'noticias')
	categoria_noticia = models.ForeignKey(Categoria, on_delete = models.CASCADE)
	fecha = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f"Titulo: {self.titulo} // Categoria: {self.categoria_noticia}"

class Comentario(models.Model):
	usuario = models.ForeignKey(Usuario, on_delete = models.CASCADE)
	texto = models.TextField(max_length = 1500)
	noticia = models.ForeignKey(Noticia, on_delete = models.CASCADE)
	fecha = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f"Usuario: {self.usuario}  //  Comentario: {self.texto}"

apps/usuarios/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):
	pass

apps/usuarios/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm
from .models import Usuario

class RegistroForm(UserCreationForm):
    email = forms.EmailField(label='Correo', required=True)
    first_name = forms.CharField(label='Nombre', required=True)
    last_name = forms.CharField(label='Apellido', required=True)
    password1 = forms.CharField(
        label='Contraseña', widget=forms.PasswordInput, required=True)
    password2 = forms.CharField(
        label='Confirmar Contraseña', widget=forms.PasswordInput, required=True)

    class Meta:
        model = Usuario
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2'
        ]

apps/noticias/views.py
from django.shortcuts import render, redirect

from django.contrib.auth.decorators import login_required

from .models import Noticia, Categoria, Comentario

from django.urls import reverse_lazy

# @login_required ==> esto hace que tenga necesidad de logearse para ingresar a noticias.
def Listar_Noticias(request):
	contexto = {}

	id_categoria = request.GET.get('id',None)

	if id_categoria:
		n = Noticia.objects.filter(categoria_noticia = id_categoria)
	else:
		n = Noticia.objects.all() #RETORNA UNA LISTA DE OBJETOS

	contexto['noticias'] = n

	cat = Categoria.objects.all().order_by('nombre')
	contexto['categorias'] = cat

	return render(request, 'noticias/listar.html', contexto)

# @login_required
def Detalle_Noticias(request, pk):
	contexto = {}

	n = Noticia.objects.get(pk = pk) #RETORNA SOLO UN OBEJTO
	contexto['noticia'] = n

	c = Comentario.objects.filter(noticia = n)
	contexto['comentarios'] = c

	return render(request, 'noticias/detalle.html',contexto)


@login_required

def Comentar_Noticia(request):

	com = request.POST.get('comentario',None)
	usu = request.user
	noti = request.POST.get('id_noticia', None)# OBTENGO LA PK
	noticia = Noticia.objects.get(pk = noti) #BUSCO LA NOTICIA CON ESA PK
	coment = Comentario.objects.create(usuario = usu, noticia = noticia, texto = com)

	return redirect(reverse_lazy('noticias:detalle', kwargs={'pk': noti}))



#{'nombre':'nicolas', 'apellido':'Tortosa', 'edad':33}
#EN EL TEMPLATE SE RECIBE UNA VARIABLE SEPARADA POR CADA CLAVE VALOR
# nombre
# apellido
# edad

'''
ORM

CLASE.objects.get(pk = ____)
CLASE.objects.filter(campos = ____)
CLASE.objects.all() ---> SELECT * FROM CLASE

'''

apps/usuarios/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import RegistroForm
# Create your views here.

class Registro(CreateView):
	#FORMULARIO DJANGO
	form_class = RegistroForm
	success_url = reverse_lazy('login')
	template_name = 'usuarios/registro.html'

blog/views.py
from django.shortcuts import render

#request 'es un diccionario que continuamente se va pasando entre el navegador y el servidor'

def Home(request):

	return render(request, 't_home.html')


def Nosotros(request):

	return render(request, 't_nosotros.html')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es"> 
<head>
	
	<title> {% block titulo %} {% endblock titulo %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico'%}">
	
	

    <!-- Bootstrap CSS -->
    <link  href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<link rel="stylesheet" href="../static/css/main.css">
</head>


<body class="contenedor">
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark"  >
		<div class="container-fluid">
			<img class="logo" src="{% static '../static/img/logo-ala.png'%}" alt="" width="50" height="50">			
		  <a class="navbar-brand" href="{% url 'home' %}">Fundación ALÁ</a>
		  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarScroll">
			<ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
			  <li class="nav-item">
				<a class="nav-link " aria-current="page" href="{% url 'home' %}">Inicio</a>
			  </li>
			  <li class="nav-item">
				<a class="nav-link" href="{% url 'nosotros' %}">Nosotros</a>
			  </li>
			  
			  <li class="nav-item">
				<a class="nav-link " href="{% url 'noticias:listar' %}" tabindex="-1" aria-disabled="true">Noticias</a>
			  </li>
			  <li class="nav-item">
				<a class="nav-link " aria-current="page" href="{% url 'admin:login' %}">Admistrar</a>
			  </li>
			  
			</ul>			
		  </div>

		  {% if user.is_authenticated %}
			<strong style="color: white" >Hola {{ user.username }}!</strong>
			
			<a href="{% url 'logout' %}"><button type="button" class="btn btn-danger">Cerrar Sesion</button></a>
		{% else %}
		  	<div>
				  <a href="{% url 'login' %}"> <button type="button" class="btn btn-success">Iniciar Sesion</button></a>	
						 
				  <a href="{% url 'usuarios:registro' %}"><button type="button" class="btn btn-primary">Registrarse</button></a>

			</div>
		{% endif %}
		</div>
	  </nav>

<!-- {% comment %} 
	<nav class="navbar navbar-dark bg-primary">
			<img src="{% static 'img/logo.png' %}" width="50px" height="50px">
		<a href="{% url 'home' %}">IR AL HOME</a>
		<a href="{% url 'nosotros' %}">IR A NOSOTROS</a>
		<a href="{% url 'noticias:listar' %}">IR A NOTICIAS</a>

		{% if user.is_authenticated %}
			<strong>Hola {{ user.username }}</strong>
			<a href="{% url 'logout' %}">LOGOUT</a>
		{% else %}
			<a href="{% url 'login' %}">LOGIN</a>
			<a href="{% url 'usuarios:registro' %}">Registrar</a>
		{% endif %}
	  </nav> {% endcomment %} -->

	

	<div class="bloque">
	{% block contenido %}
	
	{% endblock contenido %}
	</div>
	
	
	<footer class="footer">
		<div class="container">
			<div class="row">
				<div class="col-lg-7">
					<div class="widget">
						<div class="footer-text text-left">
							<a href="{% url 'home' %}"><img src="{%static 'img/logo.png'%}" alt="" width="50" height="50" class="img-fluid"></a>
							<p>Este Blog permite la difusión, visibilización y debate sobre nuestras noticias.</p>
							<div class="social">
								<a href="#" data-toggle="tooltip" data-placement="bottom" title="Facebook"><i class="fa fa-globe" aria-hidden="true"></i> www.fundacionala.com.ar</a>
							</div>

							<hr class="invis">

							<div class="newsletter-widget text-left">
								<!-- <form class="form-inline">
									<input type="text" class="form-control" placeholder="Enter your email address">
									<button type="submit" class="btn btn-primary">SUBMIT</button>
								</form> -->
							</div><!-- end newsletter -->
						</div><!-- end footer-text -->
					</div><!-- end widget -->
				</div><!-- end col -->

				<div class="col-lg-3 col-md-12 col-sm-12 col-xs-12 ml-5">
					<div class="widget">
						<h2 class="widget-title">Integrantes</h2>
						<div class="link-widget">
							<ul>
								<li><a href="https://www.linkedin.com/in/leandromalvarez/" target="_blank" >Alvarez,Leandro <span>(P.M & Dev)</span> </a></li>
								<li><a href="https://www.linkedin.com/in/pablo-swistoniuk-316761120/" target="_blank" >Swistoniuk, Pablo <span>(Video & Dev)</span> </a></li>
								<li><a href="https://www.linkedin.com/in/pablo-velizan-5237a8170/" target="_blank" >Velizan,Pablo <span>(Video & Dev)</span> </a></li>
							</ul>
						</div>
					</div>
				</div>

			</div>

			<div class="row">
				<div class="col-md-12 text-center">
					<br>
					<div class="copyright">&copy; Fundacion ALA' {% now "Y" %}. <br> {% now "d M" %}, Informatorio Chaco</div>
				</div>
			</div>
		</div><!-- end container -->
	</footer><!-- end footer -->
	
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

templates/noticias/detalle.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}NOTICIAS{% endblock titulo %}


{% block contenido %}
<!-- <h1>ACA VOY A DETALLAR UNA NOTICIA</h1> -->

<div class="card">
	<div class="card-body">
		<center>
			<h2 class="card-title">{{noticia.titulo}}</h2>
			<hr>
			<h4 class="card-text" >{{noticia.cuerpo}}</h4>
		</center>
		<p class="card-text"><small class="text-muted">Categoria: {{noticia.categoria_noticia}}</small></p>
		<p class="card-text"><small class="text-muted">{{noticia.fecha}}</small></p>
	</div>
	<img src="{{noticia.imagen.url}}" class="card-img-bottom" alt="...">
</div>

			<form method="POST" action="{% url 'noticias:comentar' %}">{% csrf_token %}
			
			{% comment %} <textarea name="comentario" maxlength="1500"> </textarea> {% endcomment %}


			<div class="form-floating">
				<textarea class="form-control" name="comentario" maxlength="1500" width='50px'></textarea>
				
			  </div>


			<input type="text" name="id_noticia" value="{{noticia.pk}}" hidden=""> 
			{% comment %} <input type="submit" value="Comentar"> {% endcomment %}
			<button type="submit"  value="Comentar" class="btn btn-outline-primary">Comentar</button>
		</form>
		<br><br><br>
		<h3>COMENTARIOS</h3>
		{% for com in comentarios %}
		{% if user == com.usuario %}
			{% comment %} <a href="">borrar</a> {% endcomment %}
		{% endif %}
		<strong>FECHA:{{com.fecha}}</strong><br>
		<strong>USUARIO:{{com.usuario}}</strong><br>
		<p>{{com.texto}}</p>
		{% endfor %}
		<a href="{% url 'noticias:listar' %}">VOLVER</a>
{% endblock contenido %}

templates/noticias/listar.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}NOTICIAS{% endblock titulo %}

{% block contenido %}
	<div class="submenu">

		<a href="{% url 'noticias:listar' %}">TODAS</a>
		{% for cat in categorias %}
			<a href="?id={{cat.pk}}">{{cat.nombre}}</a>
		{% endfor %}
	</div>



	




	{% for noti in noticias %}

	<center>
	 
	  <div class="card mb-3" style="max-width: 540px;">
		<div class="row g-0">
		  <div class="col-md-4">
			<img src="{{noti.imagen.url}}" class="img-fluid rounded-start" alt="imagen-noticia">
		  </div>
		  <div class="col-md-8">
			<div class="card-body">
			  <h5 class="card-title"><a href="{% url 'noticias:detalle' noti.pk %}">{{noti.titulo}}</a></h5>
			  <p class="card-text"> {{noti.cuerpo}}</p>
			  <p>Categoria: {{noti.categoria_noticia}}</p>
			  <p class="card-text"><small class="text-muted">{{noti.fecha}}</small></p>
			  <br><br>
			</div>
		  </div>
		</div>
	  </div>
	 
	</center>
	{% endfor %}
{% endblock contenido %}

templates/t_home.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}Pagina Principal{% endblock titulo %}


{% block contenido %}
	<center>
		<br>
		<img src="{% static './img/fundacion-significado.jpg' %}"
		width="500" height="500"
		alt="texto alternativo de la imagen" />
		<br><br><br><br><br><br>
	</center>
	

	
{% endblock contenido %}

templates/t_nosotros.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}Nosotros{% endblock titulo %}


{% block contenido %}
<center>
	
	<div>
		<h1>ALA' (significa SEMILLA en idioma Qom)</h1>
		<hr>
		<h2>Responsables: </h2>
		<h3>Presidente : <strong>Felicia Del Carmen Sambrana</strong>  </h3>
		<h3>Tesorero: <strong>Arevalo Antolin Edy </strong> </h3>
		<h3>Secretario : <strong>Miguel Amadeo Barrios</strong>  </h3>
			</div>
		<br><br><br><br><br><br><br><br><br><br>
</center>
	
{% endblock contenido %}

templates/usuarios/login.html
{% extends 'base.html' %}

{% block contenido %}
			<form method="POST">{%csrf_token%}
				{{form.errors}}
				<input type="text" name="username" placeholder="USUARIO">
				<input type="password" name="password" placeholder="PASSWORD">

				<input type="submit" name="" value="ENVIAR">
			</form>
{% endblock %}

templates/usuarios/registro.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Registro{% endblock %}
{% block contenido %}

<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto mb-5">
        <form action="" method="post">{% csrf_token %}         
         <h3 class="mb-4">Registro</h3>
          {{form.as_p}}
          <p><input type="submit" class="btn btn-primary btn-block" value="Confirmar"></p>
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock contenido %}